////////////////////////////////////////////////////////////////////////////////
//
// espresso.hxx
//
////////////////////////////////////////////////////////////////////////////////
//
// Developed by Donnacha Forde (@DonnachaForde)
//
// Copyright � 1993-2020, Donnacha Forde. All rights reserved.
//
//
// This software is provided 'as is' without warranty, expressed or implied.
// Donnacha Forde accepts no responsibility for the use or reliability of this software. 
// 
////////////////////////////////////////////////////////////////////////////////


#ifndef INCLUDED_ESPRESSO_HXX
#define INCLUDED_ESPRESSO_HXX

// VC++ one time include
#if _MSC_VER > 1000
	#pragma once
#endif 


////////////////////////////////////////////////////////////////////////////////
// 
// warning levels 
//
// Note: #include CRT headers before this header may still result in the disabled warnings below being seen.
//

#ifdef WIN32

	#ifndef ESPRESSO_ENABLE_WARNINGS

		// let developer know we're implicity disabling some warnings
		#if defined(DEBUG) || defined(_DEBUG)
			#pragma message("note : Disabling some common warnings generated by using the STL.")
		#endif
		
		#pragma warning( disable : 4786 ) // Ignore string too long caused by STL declarations
		#pragma warning( disable : 4503 ) // Ignore 'decorated name length exceeded and truncated' (template names can be very long)

		// need to disable these warning with newer, fuzzier compilers, otherwise can't use things like strcpy, sprintf, etc.
		#pragma message("note : CRT security warning (so we can use ol' fashioned 'C' calls)")
		#define _CRT_SECURE_NO_WARNINGS

		#pragma message("note : Suppress warnings about deprecated POSIX function names.")
		#pragma warning(suppress : 4996)

	#else

		#pragma warning( default : 4786 ) // Ignore string too long caused by STL declarations
		#pragma warning( default : 4503 ) // Ignore 'decorated name length exceeded and truncated' (template names can be very long)
	
	#endif // ESPRESSO_ENABLE_WARNINGS

#endif // WIN32


////////////////////////////////////////////////////////////////////////////////
// 
// headers
//

// forward declaration 
namespace espresso {}

#ifndef INCLUDED_ESPRESSO_ARGS_HXX
#include <espresso/Args.hxx>
#define INCLUDED_ESPRESSO_ARGS_HXX
#endif


#ifndef INCLUDED_ESPRESSO_ARGMGRCLI_HXX
#include <espresso/ArgMgr.hxx>
#define INCLUDED_ESPRESSO_ARGMGRCLI_HXX
#endif

#ifndef INCLUDED_ESPRESSO_ARGMANAGERFACTORY_HXX
#include <espresso/ArgManagerFactory.hxx>
#define INCLUDED_ESPRESSO_ARGMANAGERFACTORY_HXX
#endif


#ifndef INCLUDED_ESPRESSO_STDOUTARGRENDERER_HXX
#include <espresso/StdoutArgRenderer.hxx>
#define ININCLUDED_ESPRESSO_STDOUTARGRENDERER_HXX
#endif


#ifndef INCLUDED_ESPRESSO_STRINGS_HXX
#include <espresso/strings.hxx>
#define INCLUDED_ESPRESSO_STRINGS_HXX
#endif


#ifndef INCLUDED_ESPRESSO_TIME_HXX
#include <espresso/time.hxx>
#define INCLUDED_ESPRESSO_TIME_HXX
#endif





////////////////////////////////////////////////////////////////////////////////
// 
// porting/platform descrepencies 
//





#endif // INCLUDED_ESPRESSO_HXX

